# Generated by Django 5.1.7 on 2026-03-10 13:15

import django.db.models.deletion
import django.utils.timezone
import fiscal_regras.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraAliquotaICMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255)),
                ('ncm_prefixo', models.CharField(max_length=8, validators=[fiscal_regras.validators.validate_ncm_prefixo])),
                ('prefixo_len', models.PositiveSmallIntegerField(editable=False)),
                ('tipo_operacao', models.CharField(blank=True, choices=[('0', 'Entrada'), ('1', 'Saida')], max_length=1, null=True)),
                ('modalidade', models.CharField(blank=True, choices=[('interna', 'Interna'), ('interestadual', 'Interestadual')], max_length=20, null=True)),
                ('uf_origem', models.CharField(blank=True, max_length=2, null=True)),
                ('uf_destino', models.CharField(blank=True, max_length=2, null=True)),
                ('origem_mercadoria', models.CharField(blank=True, max_length=1, null=True)),
                ('aliquota_icms', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fcp', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reducao_base_icms', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prioridade', models.IntegerField(default=0)),
                ('vigencia_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_aliquota_icms_criadas', to=settings.AUTH_USER_MODEL)),
                ('csosn_icms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_icms_csosn', to='fiscal.csosn')),
                ('cst_icms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_icms_cst', to='fiscal.cst')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_aliquota_icms_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra de Aliquota ICMS',
                'verbose_name_plural': 'Regras de Aliquota ICMS',
                'ordering': ['-ativo', '-prioridade', '-prefixo_len', 'descricao'],
                'permissions': [('override_aliquota_item', 'Pode sobrescrever aliquota automatica do item')],
                'indexes': [models.Index(fields=['ativo', 'vigencia_inicio', 'vigencia_fim'], name='fiscal_regr_ativo_45f731_idx'), models.Index(fields=['ncm_prefixo', 'prefixo_len'], name='fiscal_regr_ncm_pre_966114_idx'), models.Index(fields=['modalidade', 'uf_origem', 'uf_destino'], name='fiscal_regr_modalid_9e8c92_idx'), models.Index(fields=['tipo_operacao', 'prioridade'], name='fiscal_regr_tipo_op_ec9cab_idx')],
            },
        ),
    ]
