# Generated by Django 5.1.7 on 2025-04-26 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0005_empresaavancada_categoria_empresaavancada_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('natureza_operacao', models.CharField(max_length=255)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('chave_acesso', models.CharField(max_length=50, unique=True)),
                ('valor_total_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total_nota', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total_icms', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total_pis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('informacoes_adicionais', models.TextField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fornecedor', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DuplicataNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vencimento', models.DateField()),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicatas', to='nota_fiscal.notafiscal')),
            ],
        ),
        migrations.CreateModel(
            name='TransporteNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade_frete', models.CharField(blank=True, choices=[('0', 'Contratação do Frete por Conta do Remetente (CIF)'), ('1', 'Contratação do Frete por Conta do Destinatário (FOB)'), ('2', 'Contratação do Frete por Conta de Terceiros'), ('9', 'Sem Ocorrência de Transporte')], max_length=2, null=True)),
                ('transportadora_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('transportadora_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('placa_veiculo', models.CharField(blank=True, max_length=10, null=True)),
                ('uf_veiculo', models.CharField(blank=True, max_length=2, null=True)),
                ('rntc', models.CharField(blank=True, max_length=20, null=True)),
                ('quantidade_volumes', models.PositiveIntegerField(default=0)),
                ('especie_volumes', models.CharField(blank=True, max_length=50, null=True)),
                ('peso_liquido', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('peso_bruto', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('nota_fiscal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporte', to='nota_fiscal.notafiscal')),
            ],
        ),
    ]
