# Generated by Django 5.1.7 on 2026-01-18 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicataNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número da Duplicata')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
            ],
            options={
                'verbose_name': 'Duplicata da Nota Fiscal',
                'verbose_name_plural': 'Duplicatas da Nota Fiscal',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('numero', models.CharField(max_length=20, verbose_name='Número da NF')),
                ('natureza_operacao', models.CharField(max_length=255, verbose_name='Natureza da Operação')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída/Entrada')),
                ('chave_acesso', models.CharField(max_length=44, unique=True, verbose_name='Chave de Acesso')),
                ('raw_payload', models.JSONField(blank=True, help_text='JSON puro extraído do infNFe', null=True, verbose_name='Payload bruto da importação')),
                ('tipo_operacao', models.CharField(blank=True, choices=[('0', 'Entrada'), ('1', 'Saída')], max_length=1, null=True, verbose_name='Tipo de Operação')),
                ('finalidade_emissao', models.CharField(blank=True, choices=[('1', 'NF-e normal'), ('2', 'NF-e complementar'), ('3', 'NF-e de ajuste'), ('4', 'Devolução de mercadoria')], max_length=1, null=True, verbose_name='Finalidade da Emissão')),
                ('modelo_documento', models.CharField(blank=True, choices=[('55', 'NF-e'), ('65', 'NFC-e')], max_length=2, null=True, verbose_name='Modelo do Documento Fiscal')),
                ('serie', models.CharField(blank=True, max_length=5, null=True, verbose_name='Série da NF')),
                ('ambiente', models.CharField(blank=True, choices=[('1', 'Produção'), ('2', 'Homologação')], max_length=1, null=True, verbose_name='Ambiente de Emissão')),
                ('protocolo_autorizacao', models.CharField(blank=True, max_length=15, null=True, verbose_name='Protocolo de Autorização')),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Autorização')),
                ('status_sefaz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status SEFAZ')),
                ('motivo_status_sefaz', models.TextField(blank=True, null=True, verbose_name='Motivo Status SEFAZ')),
                ('id_servico_terceiro', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Serviço Terceiro')),
                ('valor_total_produtos', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total dos Produtos')),
                ('valor_total_nota', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total da Nota')),
                ('valor_total_icms', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total ICMS')),
                ('valor_total_pis', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total PIS')),
                ('valor_total_cofins', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total COFINS')),
                ('valor_total_desconto', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total Desconto')),
                ('informacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_emissao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='TransporteNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade_frete', models.CharField(blank=True, choices=[('0', 'Contratação do Frete por conta do Remetente (CIF)'), ('1', 'Contratação do Frete por conta do Destinatário (FOB)'), ('2', 'Contratação do Frete por conta de Terceiros'), ('3', 'Transporte Próprio por conta do Remetente'), ('4', 'Transporte Próprio por conta do Destinatário'), ('9', 'Sem Ocorrência de Transporte')], max_length=2, null=True, verbose_name='Modalidade do Frete')),
                ('transportadora_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Transportadora')),
                ('transportadora_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ Transportadora')),
                ('placa_veiculo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo')),
                ('uf_veiculo', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do Veículo')),
                ('rntc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RNTC')),
                ('quantidade_volumes', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Volumes')),
                ('especie_volumes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Espécie dos Volumes')),
                ('peso_liquido', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Peso Líquido (kg)')),
                ('peso_bruto', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Peso Bruto (kg)')),
            ],
            options={
                'verbose_name': 'Transporte da Nota Fiscal',
                'verbose_name_plural': 'Transportes da Nota Fiscal',
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código do Produto')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Produto')),
                ('ncm', models.CharField(blank=True, max_length=10, null=True, verbose_name='NCM')),
                ('cfop', models.CharField(blank=True, max_length=10, null=True, verbose_name='CFOP')),
                ('unidade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade Comercial')),
                ('quantidade', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Valor Total')),
                ('desconto', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Valor Desconto')),
                ('base_calculo_icms', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Base Cálculo ICMS')),
                ('aliquota_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota ICMS (%)')),
                ('valor_icms_desonerado', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor ICMS Desonerado')),
                ('motivo_desoneracao_icms', models.CharField(blank=True, max_length=2, null=True, verbose_name='Motivo Desoneração ICMS')),
                ('base_calculo_ipi', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Base Cálculo IPI')),
                ('aliquota_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota IPI (%)')),
                ('base_calculo_pis', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Base Cálculo PIS')),
                ('aliquota_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota PIS (%)')),
                ('base_calculo_cofins', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Base Cálculo COFINS')),
                ('aliquota_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota COFINS (%)')),
                ('informacoes_adicionais_item', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais do Item')),
                ('cst_cofins_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_cofins_cst', to='fiscal.cst', verbose_name='CST COFINS Aplicado')),
                ('cst_icms_csosn_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_icms_csosn', to='fiscal.csosn', verbose_name='CSOSN ICMS Aplicado')),
                ('cst_icms_cst_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_icms_cst', to='fiscal.cst', verbose_name='CST ICMS Aplicado')),
                ('cst_ipi_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_ipi_cst', to='fiscal.cst', verbose_name='CST IPI Aplicado')),
                ('cst_pis_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pis_cst', to='fiscal.cst', verbose_name='CST PIS Aplicado')),
            ],
        ),
    ]
