# Generated by Django 5.1.7 on 2025-07-05 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('nota_fiscal', '0001_initial'),
        ('produto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnotafiscal',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_nota', to='produto.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_recebidas', to='empresas.empresaavancada', verbose_name='Destinatário'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='emitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_emitidas', to='empresas.empresaavancada', verbose_name='Emitente (Fornecedor)'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nota_fiscal.notafiscal', verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='duplicatanotafiscal',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicatas', to='nota_fiscal.notafiscal', verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='transportenotafiscal',
            name='nota_fiscal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporte', to='nota_fiscal.notafiscal', verbose_name='Nota Fiscal'),
        ),
        migrations.AlterUniqueTogether(
            name='duplicatanotafiscal',
            unique_together={('nota_fiscal', 'numero')},
        ),
    ]
