# Generated by Django 5.1.7 on 2025-04-26 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresaavancada_categoria_empresaavancada_cliente_and_more'),
        ('nota_fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fornecedor', to='empresas.empresaavancada'),
        ),
    ]
