# Generated by Django 5.1.7 on 2025-11-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_emitente'),
        ('empresas', '0003_alter_categoriaempresa_nome'),
        ('nota_fiscal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='emitente_proprio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_proprias_emitidas', to='control.emitente', verbose_name='Nosso Emitente (Matriz/Filial)'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_recebidas', to='empresas.empresaavancada', verbose_name='Destinatário (Cliente)'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='emitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_emitidas_por_terceiros', to='empresas.empresaavancada', verbose_name='Emitente (Fornecedor)'),
        ),
    ]
