# Generated by Django 5.1.7 on 2025-04-27 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0003_notafiscal_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Entrada'),
            preserve_default=False,
        ),
    ]
