# Generated by Django 5.1.7 on 2026-03-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0003_update_empresa_relation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='condicao_pagamento',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Condicao de Pagamento'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='quantidade_parcelas',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade de Parcelas'),
        ),
    ]
