# Generated by Django 5.1.7 on 2026-03-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_regras', '0001_initial'),
        ('nota_fiscal', '0004_notafiscal_condicao_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnotafiscal',
            name='aliquota_icms_origem',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Origem da Aliquota ICMS'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='dados_contexto_regra',
            field=models.JSONField(blank=True, null=True, verbose_name='Contexto da Regra Fiscal'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='motor_versao',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Versao do Motor Fiscal'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='regra_icms_aplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_nota_aplicados', to='fiscal_regras.regraaliquotaicms', verbose_name='Regra ICMS Aplicada'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='regra_icms_descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descricao da Regra ICMS'),
        ),
    ]
