# Generated by Django 5.1.7 on 2025-04-29 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0004_notafiscal_created_at'),
        ('produto', '0012_alter_entradaproduto_cofins_aliquota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('ncm', models.CharField(blank=True, max_length=10, null=True)),
                ('cfop', models.CharField(blank=True, max_length=10, null=True)),
                ('unidade', models.CharField(blank=True, max_length=10, null=True)),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('icms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nota_fiscal.notafiscal')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_nota', to='produto.produto')),
            ],
        ),
    ]
