# Generated by Django 5.1.7 on 2026-03-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_rename_empresa_table'),
        ('nota_fiscal', '0005_itemnotafiscal_aliquota_icms_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportenotafiscal',
            name='transportadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportes', to='empresas.empresa', verbose_name='Cadastro da Transportadora'),
        ),
    ]
