# Generated by Django 5.1.7 on 2025-04-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0005_itemnotafiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatanotafiscal',
            name='valor',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='icms',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='ipi',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='quantidade',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='valor_total',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_cofins',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_desconto',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_icms',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_nota',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_pis',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_produtos',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
    ]
