# Generated by Django 5.1.7 on 2025-05-08 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresaavancada_categoria_empresaavancada_cliente_and_more'),
        ('nota_fiscal', '0006_alter_duplicatanotafiscal_valor_and_more'),
        ('produto', '0014_remove_produto_nota_fiscal_alter_produto_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('preco_unitario', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('preco_total', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('numero_nota', models.CharField(blank=True, max_length=50, null=True)),
                ('icms_valor', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('icms_aliquota', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('pis_valor', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('pis_aliquota', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('cofins_valor', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('cofins_aliquota', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresaavancada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
    ]
