# Generated by Django 5.1.7 on 2025-05-11 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0007_entradaproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproduto',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_estoque', to='nota_fiscal.notafiscal'),
        ),
    ]
