# Generated by Django 5.1.7 on 2025-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0008_entradaproduto_nota_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='raw_payload',
            field=models.JSONField(blank=True, help_text='JSON puro extraído do infNFe', null=True, verbose_name='Payload bruto da importação'),
        ),
    ]
