# Generated by Django 5.1.7 on 2025-06-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0009_notafiscal_raw_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaproduto',
            name='cofins_aliquota',
        ),
        migrations.RemoveField(
            model_name='entradaproduto',
            name='cofins_valor',
        ),
        migrations.RemoveField(
            model_name='entradaproduto',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='entradaproduto',
            name='icms_aliquota',
        ),
        migrations.RemoveField(
            model_name='entradaproduto',
            name='icms_valor',
        ),
        migrations.RemoveField(
            model_name='entradaproduto',
            name='nota_fiscal',
        ),
        migrations.RemoveField(
            model_name='entradaproduto',
            name='numero_nota',
        ),
        migrations.RemoveField(
            model_name='entradaproduto',
            name='pis_aliquota',
        ),
        migrations.RemoveField(
            model_name='entradaproduto',
            name='pis_valor',
        ),
        migrations.AddField(
            model_name='entradaproduto',
            name='item_nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_produto', to='nota_fiscal.itemnotafiscal'),
        ),
    ]
