# Generated by Django 5.1.7 on 2025-06-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0010_remove_entradaproduto_cofins_aliquota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnotafiscal',
            name='cofins',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='pis',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='icms',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='ipi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
