# Generated by Django 5.1.7 on 2025-07-01 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresaavancada_categoria_empresaavancada_cliente_and_more'),
        ('nota_fiscal', '0011_itemnotafiscal_cofins_itemnotafiscal_pis_and_more'),
        ('produto', '0017_remove_produto_codigo_produto_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duplicatanotafiscal',
            options={'verbose_name': 'Duplicata da Nota Fiscal', 'verbose_name_plural': 'Duplicatas da Nota Fiscal'},
        ),
        migrations.AlterModelOptions(
            name='entradaproduto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrada de Produto', 'verbose_name_plural': 'Entradas de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='itemnotafiscal',
            options={'verbose_name': 'Item da Nota Fiscal', 'verbose_name_plural': 'Itens da Nota Fiscal'},
        ),
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'ordering': ['-data_emissao', '-numero'], 'verbose_name': 'Nota Fiscal', 'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='transportenotafiscal',
            options={'verbose_name': 'Transporte da Nota Fiscal', 'verbose_name_plural': 'Transportes da Nota Fiscal'},
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_recebidas', to='empresas.empresaavancada', verbose_name='Destinatário'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='emitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_emitidas', to='empresas.empresaavancada', verbose_name='Emitente (Fornecedor)'),
        ),
        migrations.AlterField(
            model_name='duplicatanotafiscal',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicatas', to='nota_fiscal.notafiscal', verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='duplicatanotafiscal',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número da Duplicata'),
        ),
        migrations.AlterField(
            model_name='duplicatanotafiscal',
            name='valor',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='duplicatanotafiscal',
            name='vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Entrada'),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='item_nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_produto', to='nota_fiscal.itemnotafiscal', verbose_name='Item da Nota Fiscal Associado'),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='preco_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Preço Total na Entrada'),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Preço Unitário na Entrada'),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Quantidade Entrada'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='cfop',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CFOP'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='cofins',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor COFINS'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Valor Desconto'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição do Produto'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='icms',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor ICMS'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='ipi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor IPI'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='ncm',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nota_fiscal.notafiscal', verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='pis',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor PIS'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_nota', to='produto.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='unidade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade Comercial'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='valor_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_acesso',
            field=models.CharField(max_length=44, unique=True, verbose_name='Chave de Acesso'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='data_saida',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Saída/Entrada'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='informacoes_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Adicionais'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='natureza_operacao',
            field=models.CharField(max_length=255, verbose_name='Natureza da Operação'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número da NF'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_cofins',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total COFINS'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_desconto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total Desconto'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_icms',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total ICMS'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_nota',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total da Nota'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_pis',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total PIS'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_total_produtos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total dos Produtos'),
        ),
        migrations.AlterField(
            model_name='transportenotafiscal',
            name='especie_volumes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Espécie dos Volumes'),
        ),
        migrations.AlterField(
            model_name='transportenotafiscal',
            name='modalidade_frete',
            field=models.CharField(blank=True, choices=[('0', 'Contratação do Frete por conta do Remetente (CIF)'), ('1', 'Contratação do Frete por conta do Destinatário (FOB)'), ('2', 'Contratação do Frete por conta de Terceiros'), ('3', 'Transporte Próprio por conta do Remetente'), ('4', 'Transporte Próprio por conta do Destinatário'), ('9', 'Sem Ocorrência de Transporte')], max_length=2, null=True, verbose_name='Modalidade do Frete'),
        ),
        migrations.AlterField(
            model_name='transportenotafiscal',
            name='nota_fiscal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporte', to='nota_fiscal.notafiscal', verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='transportenotafiscal',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Peso Bruto (kg)'),
        ),
        migrations.AlterField(
            model_name='transportenotafiscal',
            name='peso_liquido',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Peso Líquido (kg)'),
        ),
        migrations.AlterField(
            model_name='transportenotafiscal',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo'),
        ),
        migrations.AlterField(
            model_name='transportenotafiscal',
            name='quantidade_volumes',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de Volumes'),
        ),
        migrations.AlterField(
            model_name='transportenotafiscal',
            name='rntc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RNTC'),
        ),
        migrations.AlterField(
            model_name='transportenotafiscal',
            name='transportadora_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ Transportadora'),
        ),
        migrations.AlterField(
            model_name='transportenotafiscal',
            name='transportadora_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Transportadora'),
        ),
        migrations.AlterField(
            model_name='transportenotafiscal',
            name='uf_veiculo',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do Veículo'),
        ),
        migrations.AlterUniqueTogether(
            name='duplicatanotafiscal',
            unique_together={('nota_fiscal', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='itemnotafiscal',
            unique_together={('nota_fiscal', 'codigo')},
        ),
    ]
