# Generated by Django 5.1.7 on 2025-07-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0012_alter_duplicatanotafiscal_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntradaProduto',
        ),
    ]
