# Generated by Django 5.1.7 on 2025-03-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
    ]
