# Generated by Django 5.1.7 on 2025-07-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp para recuperação de senha.', max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
