# Generated by Django 5.1.7 on 2025-07-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_groupprofile'),
    ]

    operations = [
    ]
