# Generated by Django 5.1.7 on 2025-04-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_grupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grupos',
        ),
    ]
