# Generated by Django 5.1.7 on 2025-11-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_whatsapp'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
    ]
