# Generated by Django 5.1.7 on 2025-07-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cfop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código CFOP')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'CFOP',
                'verbose_name_plural': 'CFOPs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CSOSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='Código CSOSN')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'CSOSN',
                'verbose_name_plural': 'CSOSNs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código CST')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'CST',
                'verbose_name_plural': 'CSTs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='NaturezaOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código Interno')),
                ('descricao', models.TextField(verbose_name='Descrição da Natureza de Operação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Natureza de Operação',
                'verbose_name_plural': 'Naturezas de Operação',
                'ordering': ['descricao'],
            },
        ),
    ]
