# Generated by Django 5.1.7 on 2025-07-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='unidade_medida',
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida_interna',
            field=models.ForeignKey(blank=True, help_text='Unidade de medida para controle interno de estoque.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produto.unidademedida'),
        ),
        migrations.CreateModel(
            name='FatorConversaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_fornecedor', models.CharField(help_text='Unidade de medida usada pelo fornecedor (ex: CX, FARDO)', max_length=10)),
                ('fator_conversao', models.DecimalField(decimal_places=10, default=1, help_text="Quantas unidades internas correspondem a uma unidade do fornecedor. Ex: Se a unidade do fornecedor é 'CX' com 12 itens, o fator é 12.", max_digits=18)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatores_conversao', to='empresas.empresaavancada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatores_conversao', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Fator de Conversão por Fornecedor',
                'verbose_name_plural': 'Fatores de Conversão por Fornecedor',
                'unique_together': {('produto', 'fornecedor', 'unidade_fornecedor')},
            },
        ),
    ]
