# Generated by Django 5.1.7 on 2026-01-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_fornecedor',
            field=models.CharField(blank=True, help_text='Código do produto conforme fornecedor.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_interno',
            field=models.CharField(blank=True, editable=False, help_text='Código único interno do produto (gerado automaticamente).', max_length=50, null=True),
        ),
    ]
