# Generated by Django 5.1.7 on 2025-07-06 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('fiscal', '0001_initial'),
        ('nota_fiscal', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=15)),
                ('preco_unitario', models.DecimalField(decimal_places=10, max_digits=18)),
                ('preco_total', models.DecimalField(decimal_places=10, max_digits=18)),
                ('numero_nota', models.CharField(max_length=50)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('icms_valor', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('icms_aliquota', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('pis_valor', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('pis_aliquota', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('cofins_valor', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('cofins_aliquota', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_produto', to='empresas.empresaavancada')),
                ('item_nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_produto', to='nota_fiscal.itemnotafiscal')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_produto', to='nota_fiscal.notafiscal')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Produto', 'Produto'), ('Insumo', 'Insumo'), ('Matéria-prima', 'Matéria-prima')], default='Produto', help_text='Classificação do produto para fins operacionais.', max_length=30)),
                ('preco_custo', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('preco_venda', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('preco_medio', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('estoque_total', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('quantidade_saidas', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('estoque_atual', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('controla_estoque', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras (EAN)', max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fator_conversao', models.DecimalField(decimal_places=10, default=1, help_text='Fator para converter a unidade de compra para a unidade interna. Ex: Se compra em CX com 12 UN, o fator é 12.', max_digits=18)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produto.categoriaproduto')),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Empresa fornecedora vinculada via XML da nota fiscal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_fornecidos', to='empresas.empresaavancada')),
                ('nota_fiscal', models.ForeignKey(blank=True, help_text='Nota fiscal à qual este produto está vinculado (caso importado do XML)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='nota_fiscal.notafiscal')),
                ('unidade_medida_interna', models.ForeignKey(blank=True, help_text='Unidade de medida para controle interno de estoque.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produto.unidademedida')),
            ],
        ),
        migrations.CreateModel(
            name='DetalhesFiscaisProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_mercadoria', models.CharField(blank=True, help_text='Origem da mercadoria (0-8)', max_length=1, null=True)),
                ('aliquota_icms_interna', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota ICMS Interna (%)')),
                ('aliquota_icms_interestadual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Alíquota ICMS Interestadual (%)')),
                ('reducao_base_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Redução Base ICMS (%)')),
                ('cest', models.CharField(blank=True, help_text='Código Especificador da Substituição Tributária (CEST)', max_length=7, null=True)),
                ('cfop', models.CharField(blank=True, help_text='Código Fiscal de Operações e Prestações', max_length=10, null=True)),
                ('valor_unitario_comercial', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='Valor Unitário Comercial')),
                ('icms', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('ipi', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('pis', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('cofins', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('unidade_comercial', models.CharField(blank=True, help_text='Unidade usada na nota (ex: UN, KG)', max_length=10, null=True)),
                ('quantidade_comercial', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('codigo_produto_fornecedor', models.CharField(blank=True, help_text='Código interno do fornecedor (cProd)', max_length=100, null=True)),
                ('cst_cofins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_cofins_cst', to='fiscal.cst', verbose_name='CST COFINS')),
                ('cst_icms_csosn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_icms_csosn', to='fiscal.csosn', verbose_name='CSOSN ICMS')),
                ('cst_icms_cst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_icms_cst', to='fiscal.cst', verbose_name='CST ICMS')),
                ('cst_ipi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_ipi_cst', to='fiscal.cst', verbose_name='CST IPI')),
                ('cst_pis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_pis_cst', to='fiscal.cst', verbose_name='CST PIS')),
                ('ncm', models.ForeignKey(blank=True, help_text='Nomenclatura Comum do Mercosul', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.ncm')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_fiscais', to='produto.produto')),
            ],
        ),
    ]
