# Generated by Django 5.1.7 on 2025-07-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_produto_unidade_medida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cfop',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ncm',
        ),
        migrations.AddField(
            model_name='detalhesfiscaisproduto',
            name='cfop',
            field=models.CharField(blank=True, help_text='Código Fiscal de Operações e Prestações', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='detalhesfiscaisproduto',
            name='ncm',
            field=models.ForeignKey(blank=True, help_text='Nomenclatura Comum do Mercosul', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.ncm'),
        ),
    ]
