# Generated by Django 5.1.7 on 2025-07-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade_fornecedor_padrao',
            field=models.ForeignKey(blank=True, help_text='Unidade de medida padrão usada pelo fornecedor para este produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_unidade_fornecedor', to='produto.unidademedida'),
        ),
    ]
