# Generated by Django 5.1.7 on 2026-01-18 21:15

import uuid
from django.db import migrations

def populate_codes(apps, schema_editor):
    """
    Copies the old 'codigo' to 'codigo_fornecedor' and generates a new
    'codigo_interno' for each existing product.
    """
    Produto = apps.get_model('produto', 'Produto')
    for produto in Produto.objects.all():
        # Copy the old code, if it exists, to the new supplier code field.
        if produto.codigo and not produto.codigo_fornecedor:
            produto.codigo_fornecedor = produto.codigo
        
        # Generate a new internal code if it doesn't have one.
        if not produto.codigo_interno:
            produto.codigo_interno = str(uuid.uuid4()).replace('-', '')[:20].upper()
        
        produto.save(update_fields=['codigo_fornecedor', 'codigo_interno'])

class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_codigo_fornecedor_produto_codigo_interno'),
    ]

    operations = [
        migrations.RunPython(populate_codes, reverse_code=migrations.RunPython.noop),
    ]