# Generated by Django 5.1.7 on 2025-04-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_ncm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='descricao',
            field=models.TextField(),
        ),
    ]
