# Generated by Django 5.1.7 on 2025-07-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_unidade_fornecedor_padrao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
