# Generated by Django 5.1.7 on 2026-01-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_populate_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codigo',
        ),
    ]
