# Generated by Django 5.1.7 on 2026-01-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_remove_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_interno',
            field=models.CharField(editable=False, help_text='Código único interno do produto (gerado automaticamente).', max_length=50, unique=True),
        ),
    ]
