# Generated by Django 5.1.7 on 2025-04-24 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresaavancada_categoria_empresaavancada_cliente_and_more'),
        ('produto', '0004_alter_produto_ncm'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras (EAN)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_produto_fornecedor',
            field=models.CharField(blank=True, help_text='Código interno do fornecedor (cProd)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cofins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst',
            field=models.CharField(blank=True, help_text='Código de Situação Tributária (CST/CSOSN)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Empresa fornecedora vinculada via XML da nota fiscal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_fornecidos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='produto',
            name='icms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='ipi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='origem_mercadoria',
            field=models.CharField(blank=True, help_text='Origem da mercadoria (0-8)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='pis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_comercial',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_comercial',
            field=models.CharField(blank=True, help_text='Unidade usada na nota (ex: UN, KG)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_unitario_comercial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário Comercial'),
        ),
    ]
