# Generated by Django 5.1.7 on 2025-04-26 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresaavancada_categoria_empresaavancada_cliente_and_more'),
        ('produto', '0005_produto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('numero_nota', models.CharField(max_length=50)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('icms_valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('icms_aliquota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pis_valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pis_aliquota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cofins_valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cofins_aliquota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_fornecedor', to='empresas.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='produto.produto')),
            ],
        ),
    ]
