# Generated by Django 5.1.7 on 2026-03-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_update_empresa_relation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhesfiscaisproduto',
            name='origem_mercadoria',
            field=models.CharField(blank=True, choices=[('0', '0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8'), ('1', '1 - Estrangeira, importação direta'), ('2', '2 - Estrangeira, adquirida no mercado interno'), ('3', '3 - Nacional, conteúdo de importação superior a 40% e até 70%'), ('4', '4 - Nacional, produzida conforme processos produtivos básicos'), ('5', '5 - Nacional, conteúdo de importação até 40%'), ('6', '6 - Estrangeira, importação direta, sem similar nacional (CAMEX)'), ('7', '7 - Estrangeira, adquirida no mercado interno, sem similar nacional (CAMEX)'), ('8', '8 - Nacional, conteúdo de importação superior a 70%')], help_text='Origem da mercadoria (0-8)', max_length=1, null=True),
        ),
    ]
