# Generated by Django 5.1.7 on 2025-04-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_alter_entradaproduto_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproduto',
            name='preco_total',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
    ]
