# Generated by Django 5.1.7 on 2025-04-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_alter_produto_estoque_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cofins',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_atual',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_total',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='produto',
            name='icms',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ipi',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pis',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_medio',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_saidas',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
    ]
