# Generated by Django 5.1.7 on 2025-04-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_alter_produto_cofins_alter_produto_estoque_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproduto',
            name='cofins_aliquota',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='cofins_valor',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='icms_aliquota',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='icms_valor',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='pis_aliquota',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='pis_valor',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='preco_total',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
    ]
