# Generated by Django 5.1.7 on 2025-04-30 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0006_alter_duplicatanotafiscal_valor_and_more'),
        ('produto', '0012_alter_entradaproduto_cofins_aliquota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, help_text='Nota fiscal à qual este produto está vinculado (caso importado do XML)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='nota_fiscal.notafiscal'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_unitario_comercial',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='Valor Unitário Comercial'),
        ),
    ]
