# Generated by Django 5.1.7 on 2025-05-08 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresaavancada_categoria_empresaavancada_cliente_and_more'),
        ('produto', '0013_produto_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nota_fiscal',
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Empresa fornecedora vinculada via XML da nota fiscal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_fornecidos', to='empresas.empresaavancada'),
        ),
    ]
