# Generated by Django 5.1.7 on 2025-05-08 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_fiscal', '0007_entradaproduto'),
        ('produto', '0014_remove_produto_nota_fiscal_alter_produto_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, help_text='Nota fiscal à qual este produto está vinculado (caso importado do XML)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='nota_fiscal.notafiscal'),
        ),
    ]
