# Generated by Django 5.1.7 on 2025-05-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_produto_nota_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Produto', 'Produto'), ('Insumo', 'Insumo'), ('Matéria-prima', 'Matéria-prima')], default='Produto', help_text='Classificação do produto para fins operacionais.', max_length=30),
        ),
    ]
