# Generated by Django 5.1.7 on 2025-06-30 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_produto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codigo_produto_fornecedor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cofins',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cst',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='icms',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ipi',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='origem_mercadoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='pis',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_comercial',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidade_comercial',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_unitario_comercial',
        ),
        migrations.CreateModel(
            name='DetalhesFiscaisProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cst', models.CharField(blank=True, help_text='Código de Situação Tributária (CST/CSOSN)', max_length=5, null=True)),
                ('origem_mercadoria', models.CharField(blank=True, help_text='Origem da mercadoria (0-8)', max_length=1, null=True)),
                ('valor_unitario_comercial', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='Valor Unitário Comercial')),
                ('icms', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('ipi', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('pis', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('cofins', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('unidade_comercial', models.CharField(blank=True, help_text='Unidade usada na nota (ex: UN, KG)', max_length=10, null=True)),
                ('quantidade_comercial', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('codigo_produto_fornecedor', models.CharField(blank=True, help_text='Código interno do fornecedor (cProd)', max_length=100, null=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_fiscais', to='produto.produto')),
            ],
        ),
    ]
