# Generated by Django 5.1.7 on 2025-07-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresaavancada_categoria_empresaavancada_cliente_and_more'),
        ('nota_fiscal', '0013_delete_entradaproduto'),
        ('produto', '0017_remove_produto_codigo_produto_fornecedor_and_more'),
    ]

    operations = [
        
        
        
        migrations.RunSQL("DELETE FROM produto_entradaproduto;"),
        migrations.AlterField(
            model_name='entradaproduto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_produto', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='entradaproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
