# Generated by Django 5.1.7 on 2025-07-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0018_remove_entradaproduto_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]