# Generated by Django 5.1.7 on 2025-07-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresaavancada_categoria_empresaavancada_cliente_and_more'),
        ('produto', '0019_remove_entradaproduto_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproduto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_produto', to='empresas.empresaavancada'),
        ),
    ]