# Generated by Django 5.1.7 on 2026-03-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicaopagamento',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Codigo'),
        ),
    ]
