# Generated by Django 5.1.7 on 2025-07-27 14:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0004_remove_produto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='CurvaCrescimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome único para a curva, ex: Curva Tilápia Verão 2025', max_length=255, unique=True)),
                ('especie', models.CharField(default='', help_text='Espécie do animal, ex: Tilápia', max_length=100)),
                ('rendimento_perc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de rendimento da carcaça', max_digits=5)),
            ],
            options={
                'verbose_name': 'Curva de Crescimento',
                'verbose_name_plural': 'Curvas de Crescimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FaseProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Fase de Produção',
                'verbose_name_plural': 'Fases de Produção',
            },
        ),
        migrations.CreateModel(
            name='LinhaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Linha de Produção',
                'verbose_name_plural': 'Linhas de Produção',
            },
        ),
        migrations.CreateModel(
            name='StatusTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Status do Tanque',
                'verbose_name_plural': 'Status dos Tanques',
            },
        ),
        migrations.CreateModel(
            name='TipoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tanque',
                'verbose_name_plural': 'Tipos de Tanque',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade_inicial', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_medio_inicial', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_povoamento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_medio_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('curva_crescimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='producao.curvacrescimento')),
                ('fase_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='producao.faseproducao')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='AlimentacaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alimentacao', models.DateField()),
                ('quantidade_racao', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('produto_racao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentacoes_consumidas', to='produto.produto')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacoes_diarias', to='producao.lote')),
            ],
            options={
                'verbose_name': 'Alimentação Diária',
                'verbose_name_plural': 'Alimentações Diárias',
            },
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('profundidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(default=True)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanques', to='producao.atividade')),
                ('linha_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanques', to='producao.linhaproducao')),
                ('status_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanques', to='producao.statustanque')),
                ('tipo_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanques', to='producao.tipotanque')),
            ],
            options={
                'verbose_name': 'Tanque',
                'verbose_name_plural': 'Tanques',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='tanque_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_no_tanque', to='producao.tanque'),
        ),
        migrations.CreateModel(
            name='EventoManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Povoamento', 'Povoamento'), ('Transferencia', 'Transferência'), ('Classificacao', 'Classificação'), ('Despesca', 'Despesca'), ('Mortalidade', 'Mortalidade'), ('Outro', 'Outro')], max_length=50)),
                ('data_evento', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_medio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_manejo', to='producao.lote')),
                ('tanque_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_destino', to='producao.tanque')),
                ('tanque_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_origem', to='producao.tanque')),
            ],
            options={
                'verbose_name': 'Evento de Manejo',
                'verbose_name_plural': 'Eventos de Manejo',
            },
        ),
        migrations.CreateModel(
            name='CurvaCrescimentoDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_semana', models.IntegerField(default=0, help_text='Número do período ou semana do ciclo')),
                ('periodo_dias', models.IntegerField(default=0, help_text='Número de dias no período (ex: 7)')),
                ('peso_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Peso inicial do animal no período (em gramas)', max_digits=10)),
                ('peso_final', models.DecimalField(decimal_places=2, default=0, help_text='Peso final do animal no período (em gramas)', max_digits=10)),
                ('ganho_de_peso', models.DecimalField(decimal_places=2, default=0, help_text='Ganho de peso total no período (em gramas)', max_digits=10)),
                ('numero_tratos', models.IntegerField(default=0, help_text='Número de tratos de ração por dia')),
                ('hora_inicio', models.TimeField(default='00:00', help_text='Hora de início do primeiro trato do dia')),
                ('arracoamento_biomassa_perc', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de arraçoamento sobre a biomassa', max_digits=5)),
                ('mortalidade_presumida_perc', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de mortalidade presumida para o período', max_digits=5)),
                ('gpd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ganho de Peso Diário (g)')),
                ('tca', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Conversão Alimentar')),
                ('curva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='producao.curvacrescimento')),
                ('racao', models.ForeignKey(blank=True, help_text='Ração utilizada no período (vinculada ao cadastro de produtos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curvas_crescimento', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Detalhe da Curva de Crescimento',
                'verbose_name_plural': 'Detalhes da Curva de Crescimento',
                'ordering': ['curva', 'periodo_semana'],
                'unique_together': {('curva', 'periodo_semana')},
            },
        ),
    ]
