# Generated by Django 5.1.7 on 2026-01-18 22:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='CurvaCrescimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome único para a curva, ex: Curva Tilápia Verão 2025', max_length=255, unique=True)),
                ('especie', models.CharField(default='', help_text='Espécie do animal, ex: Tilápia', max_length=100)),
                ('rendimento_perc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de rendimento da carcaça', max_digits=5)),
                ('trato_perc_curva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de trato da curva', max_digits=5)),
                ('peso_pretendido', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Peso pretendido (em g)', max_digits=10)),
                ('trato_sabados_perc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de trato aos sábados', max_digits=5)),
                ('trato_domingos_perc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de trato aos domingos', max_digits=5)),
                ('trato_feriados_perc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de trato aos feriados', max_digits=5)),
            ],
            options={
                'verbose_name': 'Curva de Crescimento',
                'verbose_name_plural': 'Curvas de Crescimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FaseProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Fase de Produção',
                'verbose_name_plural': 'Fases de Produção',
            },
        ),
        migrations.CreateModel(
            name='LinhaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Linha de Produção',
                'verbose_name_plural': 'Linhas de Produção',
            },
        ),
        migrations.CreateModel(
            name='Malha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Malha',
                'verbose_name_plural': 'Malhas',
            },
        ),
        migrations.CreateModel(
            name='StatusTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Status do Tanque',
                'verbose_name_plural': 'Status dos Tanques',
            },
        ),
        migrations.CreateModel(
            name='TipoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tanque',
                'verbose_name_plural': 'Tipos de Tanque',
            },
        ),
        migrations.CreateModel(
            name='TipoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tela',
                'verbose_name_plural': 'Tipos de Tela',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade_inicial', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_medio_inicial', models.DecimalField(decimal_places=3, help_text='Peso médio inicial em gramas (g)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_povoamento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_medio_atual', models.DecimalField(decimal_places=3, default=0, help_text='Peso médio atual em gramas (g)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('curva_crescimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='producao.curvacrescimento')),
                ('fase_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='producao.faseproducao')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='LoteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField(help_text='A data de referência para este registro diário.')),
                ('quantidade_inicial', models.DecimalField(blank=True, decimal_places=2, help_text='Qtd. de peixes no início do dia', max_digits=10, null=True)),
                ('peso_medio_inicial', models.DecimalField(blank=True, decimal_places=3, help_text='Peso médio no início do dia (g)', max_digits=10, null=True)),
                ('biomassa_inicial', models.DecimalField(blank=True, decimal_places=3, help_text='Biomassa no início do dia (kg)', max_digits=12, null=True)),
                ('racao_sugerida_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('quantidade_projetada', models.DecimalField(blank=True, decimal_places=2, help_text='Qtd. de peixes projetada para o FIM do dia', max_digits=10, null=True)),
                ('peso_medio_projetado', models.DecimalField(blank=True, decimal_places=3, help_text='Peso médio projetado para o FIM do dia (g)', max_digits=10, null=True)),
                ('biomassa_projetada', models.DecimalField(blank=True, decimal_places=3, help_text='Biomassa projetada para o FIM do dia (kg)', max_digits=12, null=True)),
                ('gpd_projetado', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPD Projetado (g)')),
                ('gpt_projetado', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPT Projetado (g)')),
                ('conversao_alimentar_projetada', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Conversão Alimentar Projetada')),
                ('racao_realizada_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('quantidade_real', models.DecimalField(blank=True, decimal_places=2, help_text='Qtd. de peixes real no FIM do dia', max_digits=10, null=True)),
                ('peso_medio_real', models.DecimalField(blank=True, decimal_places=3, help_text='Peso médio real no FIM do dia (g)', max_digits=10, null=True)),
                ('biomassa_real', models.DecimalField(blank=True, decimal_places=3, help_text='Biomassa real no FIM do dia (kg)', max_digits=12, null=True)),
                ('gpd_real', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPD Real (g)')),
                ('gpt_real', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPT Real (g)')),
                ('conversao_alimentar_real', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Conversão Alimentar Real')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_diario', to='producao.lote')),
                ('racao_realizada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_realizados', to='produto.produto')),
                ('racao_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_sugeridos', to='produto.produto')),
                ('usuario_edicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_editados', to=settings.AUTH_USER_MODEL)),
                ('usuario_lancamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico Diário do Lote',
                'verbose_name_plural': 'Históricos Diários dos Lotes',
                'ordering': ['lote', '-data_evento'],
                'unique_together': {('lote', 'data_evento')},
            },
        ),
        migrations.CreateModel(
            name='ArracoamentoSugerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20)),
                ('data_sugestao', models.DateTimeField(auto_now_add=True)),
                ('produto_racao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.produto')),
                ('usuario_sugestao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugestoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('lote_diario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sugestao', to='producao.lotediario')),
            ],
            options={
                'verbose_name': 'Sugestão de Arraçoamento',
                'verbose_name_plural': 'Sugestões de Arraçoamento',
                'ordering': ['-data_sugestao'],
            },
        ),
        migrations.CreateModel(
            name='ArracoamentoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('data_realizacao', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(blank=True, null=True)),
                ('produto_racao', models.ForeignKey(blank=True, help_text='Ração efetivamente utilizada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.produto')),
                ('usuario_edicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arracoamentos_editados', to=settings.AUTH_USER_MODEL)),
                ('usuario_lancamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arracoamentos_lancados', to=settings.AUTH_USER_MODEL)),
                ('lote_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes', to='producao.lotediario')),
            ],
            options={
                'verbose_name': 'Arraçoamento Realizado',
                'verbose_name_plural': 'Arraçoamentos Realizados',
                'ordering': ['-data_realizacao'],
            },
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('largura', models.DecimalField(blank=True, decimal_places=2, help_text='Largura em metros (m)', max_digits=10, null=True)),
                ('comprimento', models.DecimalField(blank=True, decimal_places=2, help_text='Comprimento em metros (m)', max_digits=10, null=True)),
                ('profundidade', models.DecimalField(blank=True, decimal_places=2, help_text='Profundidade em metros (m)', max_digits=10, null=True)),
                ('metro_quadrado', models.DecimalField(blank=True, decimal_places=2, help_text='Área em metros quadrados (m²)', max_digits=12, null=True)),
                ('metro_cubico', models.DecimalField(blank=True, decimal_places=3, help_text='Volume em metros cúbicos (m³)', max_digits=12, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sequencia', models.PositiveIntegerField(blank=True, null=True)),
                ('tag_tanque', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.faseproducao')),
                ('linha_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.linhaproducao')),
                ('malha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.malha')),
                ('status_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.statustanque')),
                ('tipo_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.tipotanque')),
                ('tipo_tela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.tipotela')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.unidade')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='tanque_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_no_tanque', to='producao.tanque'),
        ),
        migrations.CreateModel(
            name='EventoManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Povoamento', 'Povoamento'), ('Transferencia', 'Transferência'), ('Classificacao', 'Classificação'), ('Despesca', 'Despesca'), ('Mortalidade', 'Mortalidade'), ('Outro', 'Outro')], max_length=50)),
                ('tipo_movimento', models.CharField(blank=True, help_text='Indica se o evento representa uma entrada ou saída de peixes.', max_length=10, null=True)),
                ('data_evento', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_medio', models.DecimalField(decimal_places=3, help_text='Peso médio em gramas (g)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_manejo', to='producao.lote')),
                ('tanque_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_destino', to='producao.tanque')),
                ('tanque_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_origem', to='producao.tanque')),
            ],
            options={
                'verbose_name': 'Evento de Manejo',
                'verbose_name_plural': 'Eventos de Manejo',
            },
        ),
        migrations.CreateModel(
            name='CurvaCrescimentoDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_semana', models.IntegerField(default=0, help_text='Número do período ou semana do ciclo')),
                ('periodo_dias', models.IntegerField(default=0, help_text='Número de dias no período (ex: 7)')),
                ('peso_inicial', models.DecimalField(decimal_places=3, default=0, help_text='Peso inicial do animal no período (em g)', max_digits=10)),
                ('peso_final', models.DecimalField(decimal_places=3, default=0, help_text='Peso final do animal no período (em g)', max_digits=10)),
                ('ganho_de_peso', models.DecimalField(decimal_places=3, default=0, help_text='Ganho de peso total no período (em g)', max_digits=10)),
                ('numero_tratos', models.IntegerField(default=0, help_text='Número de tratos de ração por dia')),
                ('hora_inicio', models.TimeField(default='00:00', help_text='Hora de início do primeiro trato do dia')),
                ('arracoamento_biomassa_perc', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de arraçoamento sobre a biomassa (%BW/dia)', max_digits=5)),
                ('mortalidade_presumida_perc', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de mortalidade presumida para o período', max_digits=5)),
                ('gpd', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Ganho de Peso Diário (g)')),
                ('tca', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Taxa de Conversão Alimentar')),
                ('curva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='producao.curvacrescimento')),
                ('racao', models.ForeignKey(blank=True, help_text='Ração utilizada no período (vinculada ao cadastro de produtos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curvas_crescimento', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Detalhe da Curva de Crescimento',
                'verbose_name_plural': 'Detalhes da Curva de Crescimento',
                'ordering': ['curva', 'periodo_semana'],
                'unique_together': {('curva', 'periodo_semana')},
            },
        ),
    ]
