# Generated by Django 5.1.7 on 2025-07-31 00:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Malha',
                'verbose_name_plural': 'Malhas',
            },
        ),
        migrations.CreateModel(
            name='TipoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tela',
                'verbose_name_plural': 'Tipos de Tela',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AddField(
            model_name='tanque',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tanque',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tanque',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.faseproducao'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='ha',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10, verbose_name='Hectares (ha)'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='metro_cubico',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='tanque',
            name='metro_quadrado',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='tanque',
            name='sequencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tanque',
            name='tag_tanque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='linha_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanques_linha_producao', to='producao.linhaproducao'),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='status_tanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanques_status', to='producao.statustanque'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='malha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.malha'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='tipo_tela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.tipotela'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.unidade'),
        ),
    ]
