# Generated by Django 5.1.7 on 2025-07-20 01:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
        ('produto', '0004_remove_produto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurvaCrescimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('produto_racao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curvas_crescimento', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Curva de Crescimento',
                'verbose_name_plural': 'Curvas de Crescimento',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade_inicial', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_medio_inicial', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_povoamento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_medio_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('curva_crescimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='producao.curvacrescimento')),
                ('fase_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='producao.faseproducao')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='AlimentacaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alimentacao', models.DateField()),
                ('quantidade_racao', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('produto_racao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentacoes_consumidas', to='produto.produto')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacoes_diarias', to='producao.lote')),
            ],
            options={
                'verbose_name': 'Alimentação Diária',
                'verbose_name_plural': 'Alimentações Diárias',
            },
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('profundidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(default=True)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanques', to='producao.atividade')),
                ('linha_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanques', to='producao.linhaproducao')),
                ('status_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanques', to='producao.statustanque')),
                ('tipo_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanques', to='producao.tipotanque')),
            ],
            options={
                'verbose_name': 'Tanque',
                'verbose_name_plural': 'Tanques',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='tanque_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_no_tanque', to='producao.tanque'),
        ),
        migrations.CreateModel(
            name='EventoManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Povoamento', 'Povoamento'), ('Transferencia', 'Transferência'), ('Classificacao', 'Classificação'), ('Despesca', 'Despesca'), ('Mortalidade', 'Mortalidade'), ('Outro', 'Outro')], max_length=50)),
                ('data_evento', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_medio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_manejo', to='producao.lote')),
                ('tanque_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_destino', to='producao.tanque')),
                ('tanque_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_origem', to='producao.tanque')),
            ],
            options={
                'verbose_name': 'Evento de Manejo',
                'verbose_name_plural': 'Eventos de Manejo',
            },
        ),
    ]
