# Generated by Django 5.1.7 on 2026-01-18 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0001_initial'),
        ('produto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arracoamentorealizado',
            name='produto_racao',
            field=models.ForeignKey(blank=True, help_text='Ração efetivamente utilizada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.produto'),
        ),
        migrations.AddField(
            model_name='arracoamentorealizado',
            name='usuario_edicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arracoamentos_editados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arracoamentorealizado',
            name='usuario_lancamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arracoamentos_lancados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arracoamentosugerido',
            name='produto_racao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.produto'),
        ),
        migrations.AddField(
            model_name='arracoamentosugerido',
            name='usuario_sugestao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugestoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curvacrescimentodetalhe',
            name='curva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='producao.curvacrescimento'),
        ),
        migrations.AddField(
            model_name='curvacrescimentodetalhe',
            name='racao',
            field=models.ForeignKey(blank=True, help_text='Ração utilizada no período (vinculada ao cadastro de produtos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curvas_crescimento', to='produto.produto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='curva_crescimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='producao.curvacrescimento'),
        ),
        migrations.AddField(
            model_name='lote',
            name='fase_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='producao.faseproducao'),
        ),
        migrations.AddField(
            model_name='eventomanejo',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_manejo', to='producao.lote'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_diario', to='producao.lote'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='racao_realizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_realizados', to='produto.produto'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='racao_sugerida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_sugeridos', to='produto.produto'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='usuario_edicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_editados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='usuario_lancamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arracoamentosugerido',
            name='lote_diario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sugestao', to='producao.lotediario'),
        ),
        migrations.AddField(
            model_name='arracoamentorealizado',
            name='lote_diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes', to='producao.lotediario'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.faseproducao'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='linha_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.linhaproducao'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='malha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.malha'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='status_tanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.statustanque'),
        ),
        migrations.AddField(
            model_name='lote',
            name='tanque_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_no_tanque', to='producao.tanque'),
        ),
        migrations.AddField(
            model_name='eventomanejo',
            name='tanque_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_destino', to='producao.tanque'),
        ),
        migrations.AddField(
            model_name='eventomanejo',
            name='tanque_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_origem', to='producao.tanque'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='tipo_tanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.tipotanque'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='tipo_tela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.tipotela'),
        ),
        migrations.AddField(
            model_name='tanque',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.unidade'),
        ),
        migrations.AlterUniqueTogether(
            name='curvacrescimentodetalhe',
            unique_together={('curva', 'periodo_semana')},
        ),
        migrations.AlterUniqueTogether(
            name='lotediario',
            unique_together={('lote', 'data_evento')},
        ),
    ]
