# Generated by Django 5.1.7 on 2026-02-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroAmbientalDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('od_1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('od_2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('od_3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('od_4', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('od_5', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temp_1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temp_2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temp_3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temp_4', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temp_5', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('amonia', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('nitrito', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('nitrato', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('alcalinidade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('od_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temp_media', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('variacao_termica', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_ambientais', to='producao.faseproducao')),
            ],
            options={
                'verbose_name': 'Parâmetro Ambiental Diário',
                'verbose_name_plural': 'Parâmetros Ambientais Diários',
                'ordering': ['-data'],
                'unique_together': {('fase', 'data')},
            },
        ),
    ]
