# Generated by Django 5.1.7 on 2025-08-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_malha_tipotela_unidade_tanque_altura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanque',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='tanque',
            name='atividade',
        ),
    ]
