# Generated by Django 5.1.7 on 2025-08-13 22:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_remove_tanque_altura_remove_tanque_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvacrescimentodetalhe',
            name='intervalo_trato_horas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Intervalo entre os tratos em horas', max_digits=4),
        ),
    ]
