# Generated by Django 5.1.7 on 2025-07-27 05:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_remove_curvacrescimento_produto_racao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curvacrescimento',
            options={'ordering': ['nome'], 'verbose_name': 'Curva de Crescimento', 'verbose_name_plural': 'Curvas de Crescimento'},
        ),
        migrations.RemoveField(
            model_name='curvacrescimento',
            name='rendimento_carcaca',
        ),
        migrations.AddField(
            model_name='curvacrescimento',
            name='rendimento_perc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de rendimento da carcaça', max_digits=5),
        ),
        migrations.AlterField(
            model_name='curvacrescimento',
            name='especie',
            field=models.CharField(default='', help_text='Espécie do animal, ex: Tilápia', max_length=100),
        ),
        migrations.AlterField(
            model_name='curvacrescimento',
            name='nome',
            field=models.CharField(help_text='Nome único para a curva, ex: Curva Tilápia Verão 2025', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='CurvaCrescimentoDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(help_text='Número do período ou semana do ciclo')),
                ('dias_periodo', models.IntegerField(help_text='Número de dias no período (ex: 7)')),
                ('peso_inicial_g', models.DecimalField(decimal_places=2, help_text='Peso inicial do animal no período (em gramas)', max_digits=10)),
                ('peso_final_g', models.DecimalField(decimal_places=2, help_text='Peso final do animal no período (em gramas)', max_digits=10)),
                ('ganho_peso_g', models.DecimalField(decimal_places=2, help_text='Ganho de peso total no período (em gramas)', max_digits=10)),
                ('tratos_diarios', models.IntegerField(help_text='Número de tratos de ração por dia')),
                ('hora_inicio_trato', models.TimeField(help_text='Hora de início do primeiro trato do dia')),
                ('arracoamento_biomassa_perc', models.DecimalField(decimal_places=2, help_text='Percentual de arraçoamento sobre a biomassa', max_digits=5)),
                ('mortalidade_presumida_perc', models.DecimalField(decimal_places=2, help_text='Percentual de mortalidade presumida para o período', max_digits=5)),
                ('tipo_racao', models.CharField(help_text='Descrição da ração utilizada no período', max_length=255)),
                ('gpd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho de Peso Diário (g)')),
                ('tca', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa de Conversão Alimentar')),
                ('curva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='producao.curvacrescimento')),
            ],
            options={
                'verbose_name': 'Detalhe da Curva de Crescimento',
                'verbose_name_plural': 'Detalhes da Curva de Crescimento',
                'ordering': ['curva', 'periodo'],
                'unique_together': {('curva', 'periodo')},
            },
        ),
        migrations.DeleteModel(
            name='DetalheCurvaCrescimento',
        ),
    ]
