# Generated by Django 5.1.7 on 2026-02-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_parametroambientaldiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotediario',
            name='fator_ambiente',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Fator total de ajuste ambiental aplicado na sugestão (ex: 0.85)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='fator_manejo',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Fator de manejo (acima/abaixo/100%) aplicado na sugestão (ex: 1.00)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='od_medio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='racao_sugerida_ajustada_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Ração sugerida ajustada por ambiente/manejo (kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='temp_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='temp_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='temp_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='variacao_termica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
