# Generated by Django 5.1.7 on 2025-08-13 22:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_curvacrescimentodetalhe_intervalo_trato_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvacrescimento',
            name='peso_pretendido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peso final pretendido para os animais nesta curva', max_digits=10),
        ),
        migrations.AddField(
            model_name='curvacrescimento',
            name='trato_domingos_perc',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentual de trato aos domingos', max_digits=5),
        ),
        migrations.AddField(
            model_name='curvacrescimento',
            name='trato_feriados_perc',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentual de trato em feriados', max_digits=5),
        ),
        migrations.AddField(
            model_name='curvacrescimento',
            name='trato_perc_curva',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentual de trato aplicado à curva inteira', max_digits=5),
        ),
        migrations.AddField(
            model_name='curvacrescimento',
            name='trato_sabados_perc',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentual de trato aos sábados', max_digits=5),
        ),
    ]
