# Generated by Django 5.1.7 on 2026-02-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_lotediario_fator_ambiente_lotediario_fator_manejo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arracoamentorealizado',
            name='data_evento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
