# Generated by Django 5.1.7 on 2025-08-20 01:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_curvacrescimento_peso_pretendido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curvacrescimentodetalhe',
            name='intervalo_trato_horas',
        ),
        migrations.AlterField(
            model_name='curvacrescimento',
            name='peso_pretendido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peso pretendido (em gramas)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='curvacrescimento',
            name='trato_domingos_perc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de trato aos domingos', max_digits=5),
        ),
        migrations.AlterField(
            model_name='curvacrescimento',
            name='trato_feriados_perc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de trato aos feriados', max_digits=5),
        ),
        migrations.AlterField(
            model_name='curvacrescimento',
            name='trato_perc_curva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de trato da curva', max_digits=5),
        ),
        migrations.AlterField(
            model_name='curvacrescimento',
            name='trato_sabados_perc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de trato aos sábados', max_digits=5),
        ),
    ]
