# Generated by Django 5.1.7 on 2026-02-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_arracoamentorealizado_data_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arracoamentorealizado',
            name='data_realizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
