# Generated by Django 5.1.7 on 2025-09-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0006_remove_curvacrescimentodetalhe_intervalo_trato_horas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanque',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='tanque',
            name='tipo_tela',
        ),
        migrations.AddField(
            model_name='eventomanejo',
            name='tipo_movimento',
            field=models.CharField(blank=True, choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], help_text='Indica se o evento representa uma entrada ou saída de peixes.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='linha_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.linhaproducao'),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='metro_cubico',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='metro_quadrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='profundidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='sequencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='status_tanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.statustanque'),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='tipo_tanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.tipotanque'),
        ),
    ]
