# Generated by Django 5.1.7 on 2026-02-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0006_alter_arracoamentorealizado_data_realizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventomanejo',
            name='transferencia_total',
            field=models.BooleanField(default=False, help_text='Marque se esta é uma transferência total, que desativará o lote de origem.'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='tanque',
            field=models.ForeignKey(blank=True, help_text='Tanque em que o lote se encontrava nesta data. Garante a precisão histórica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.tanque'),
        ),
    ]
