# Generated by Django 5.1.7 on 2025-09-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0007_alter_tanque_options_remove_tanque_tipo_tela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomanejo',
            name='tipo_movimento',
            field=models.CharField(blank=True, help_text='Indica se o evento representa uma entrada ou saída de peixes.', max_length=10, null=True),
        ),
    ]
