# Generated by Django 5.1.7 on 2026-02-28 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0008_tipoevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomanejo',
            name='tipo_evento',
            field=models.ForeignKey(blank=True, help_text='Tipo do evento de manejo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_manejo', to='producao.tipoevento'),
        ),
    ]
