# Generated by Django 5.1.7 on 2025-09-02 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0008_alter_eventomanejo_tipo_movimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='tipo_tela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.tipotela'),
        ),
    ]
