# Generated by Django 5.1.7 on 2026-02-28 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0009_alter_eventomanejo_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomanejo',
            name='tipo_evento',
            field=models.ForeignKey(default=1, help_text='Tipo do evento de manejo.', on_delete=django.db.models.deletion.PROTECT, related_name='eventos_manejo', to='producao.tipoevento'),
            preserve_default=False,
        ),
    ]
