# Generated by Django 5.1.7 on 2025-09-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0009_tanque_tipo_tela'),
        ('produto', '0004_remove_produto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='A data a que este registro se refere.')),
                ('quantidade_projetada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_medio_projetado', models.DecimalField(blank=True, decimal_places=2, help_text='Peso em gramas', max_digits=10, null=True)),
                ('biomassa_projetada', models.DecimalField(blank=True, decimal_places=2, help_text='em kg', max_digits=12, null=True)),
                ('quantidade_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_medio_real', models.DecimalField(blank=True, decimal_places=2, help_text='Peso em gramas', max_digits=10, null=True)),
                ('biomassa_real', models.DecimalField(blank=True, decimal_places=2, help_text='em kg', max_digits=12, null=True)),
                ('racao_sugerida_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('racao_realizada_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_diario', to='producao.lote')),
            ],
            options={
                'verbose_name': 'Histórico Diário do Lote',
                'verbose_name_plural': 'Históricos Diários dos Lotes',
                'ordering': ['lote', 'data'],
                'unique_together': {('lote', 'data')},
            },
        ),
        migrations.CreateModel(
            name='ArracoamentoSugerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20)),
                ('data_sugestao', models.DateTimeField(auto_now_add=True)),
                ('produto_racao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.produto')),
                ('lote_diario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sugestao', to='producao.lotediario')),
            ],
            options={
                'verbose_name': 'Sugestão de Arraçoamento',
                'verbose_name_plural': 'Sugestões de Arraçoamento',
                'ordering': ['-data_sugestao'],
            },
        ),
        migrations.CreateModel(
            name='ArracoamentoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('data_realizacao', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('produto_racao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.produto')),
                ('lote_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes', to='producao.lotediario')),
            ],
            options={
                'verbose_name': 'Arraçoamento Realizado',
                'verbose_name_plural': 'Arraçoamentos Realizados',
                'ordering': ['-data_realizacao'],
            },
        ),
        migrations.CreateModel(
            name='RacaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do perfil, ex: Inicial, Crescimento, Engorda', max_length=100, unique=True)),
                ('peso_minimo_g', models.DecimalField(decimal_places=2, help_text='Peso mínimo (em gramas) para este perfil de ração.', max_digits=10)),
                ('peso_maximo_g', models.DecimalField(decimal_places=2, help_text='Peso máximo (em gramas) para este perfil de ração.', max_digits=10)),
                ('produto_racao', models.ForeignKey(blank=True, help_text='O produto de ração recomendado para esta faixa de peso.', limit_choices_to={'categoria__nome__iexact': 'Ração'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.produto')),
            ],
            options={
                'verbose_name': 'Perfil de Ração',
                'verbose_name_plural': 'Perfis de Ração',
                'ordering': ['peso_minimo_g'],
            },
        ),
    ]
