# Generated by Django 5.1.7 on 2026-03-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0010_alter_eventomanejo_tipo_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='peso_medio_atual',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='quantidade_atual',
        ),
    ]
