# Generated by Django 5.1.7 on 2025-09-12 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0010_lotediario_arracoamentosugerido_and_more'),
        ('produto', '0001_initial'), # Adicione a dependência do app produto se não estiver lá
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # LoteDiario Renames
        migrations.RenameField(
            model_name='lotediario',
            old_name='data',
            new_name='data_evento',
        ),
        migrations.RenameField(
            model_name='lotediario',
            old_name='criado_em',
            new_name='data_lancamento',
        ),
        migrations.RenameField(
            model_name='lotediario',
            old_name='atualizado_em',
            new_name='data_edicao',
        ),

        # LoteDiario New Fields
        migrations.AddField(
            model_name='lotediario',
            name='conversao_alimentar_projetada',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Conversão Alimentar Projetada'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='conversao_alimentar_real',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Conversão Alimentar Real'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='gpd_projetado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GPD Projetado (g)'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='gpd_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GPD Real (g)'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='gpt_projetado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GPT Projetado (g)'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='gpt_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GPT Real (g)'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='racao_realizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_realizados', to='produto.produto'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='racao_sugerida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_sugeridos', to='produto.produto'),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='usuario_edicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_editados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='usuario_lancamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_diarios_criados', to=settings.AUTH_USER_MODEL),
        ),

        # ArracoamentoSugerido New Fields
        migrations.AddField(
            model_name='arracoamentosugerido',
            name='usuario_sugestao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugestoes_criadas', to=settings.AUTH_USER_MODEL),
        ),

        # ArracoamentoRealizado New Fields
        migrations.AddField(
            model_name='arracoamentorealizado',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='arracoamentorealizado',
            name='data_lancamento',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arracoamentorealizado',
            name='usuario_edicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arracoamentos_editados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arracoamentorealizado',
            name='usuario_lancamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arracoamentos_lancados', to=settings.AUTH_USER_MODEL),
        ),

        # Alter unique_together for LoteDiario
        migrations.AlterUniqueTogether(
            name='lotediario',
            unique_together={('lote', 'data_evento')},
        ),
    ]