# Generated by Django 5.1.7 on 2025-09-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0011_auto_20250911_2120'),
        ('produto', '0004_remove_produto_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotediario',
            options={'ordering': ['lote', '-data_evento'], 'verbose_name': 'Histórico Diário do Lote', 'verbose_name_plural': 'Históricos Diários dos Lotes'},
        ),
        migrations.AlterField(
            model_name='arracoamentorealizado',
            name='produto_racao',
            field=models.ForeignKey(blank=True, help_text='Ração efetivamente utilizada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.produto'),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='data_evento',
            field=models.DateField(help_text='A data de referência para este registro diário.'),
        ),
        migrations.DeleteModel(
            name='AlimentacaoDiaria',
        ),
    ]
