# Generated by Django 5.1.7 on 2025-09-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0012_alter_lotediario_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RacaoPerfil',
        ),
    ]
