# Generated by Django 5.1.7 on 2025-09-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0013_delete_racaoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotediario',
            name='biomassa_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Biomassa no início do dia (kg)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='peso_medio_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso médio no início do dia (g)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lotediario',
            name='quantidade_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Qtd. de peixes no início do dia', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='biomassa_projetada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Biomassa projetada para o FIM do dia (kg)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='biomassa_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Biomassa real no FIM do dia (kg)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='data_edicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='peso_medio_projetado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso médio projetado para o FIM do dia (g)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='peso_medio_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso médio real no FIM do dia (g)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='quantidade_projetada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Qtd. de peixes projetada para o FIM do dia', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='quantidade_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Qtd. de peixes real no FIM do dia', max_digits=10, null=True),
        ),
    ]
