# Generated by Django 5.1.7 on 2025-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0014_lotediario_biomassa_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotediario',
            name='gpd_projetado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPD Projetado (kg)'),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='gpd_real',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPD Real (kg)'),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='gpt_projetado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPT Projetado (kg)'),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='gpt_real',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPT Real (kg)'),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='peso_medio_inicial',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso médio no início do dia (kg)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='peso_medio_projetado',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso médio projetado para o FIM do dia (kg)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='peso_medio_real',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso médio real no FIM do dia (kg)', max_digits=10, null=True),
        ),
    ]
