# Generated by Django 5.1.7 on 2025-09-21 16:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0015_alter_lotediario_gpd_projetado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arracoamentorealizado',
            name='data_edicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curvacrescimento',
            name='peso_pretendido',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Peso pretendido (em kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='curvacrescimentodetalhe',
            name='ganho_de_peso',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Ganho de peso total no período (em kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='curvacrescimentodetalhe',
            name='gpd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Ganho de Peso Diário (kg)'),
        ),
        migrations.AlterField(
            model_name='curvacrescimentodetalhe',
            name='peso_final',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso final do animal no período (em kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='curvacrescimentodetalhe',
            name='peso_inicial',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso inicial do animal no período (em kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='curvacrescimentodetalhe',
            name='tca',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Taxa de Conversão Alimentar'),
        ),
        migrations.AlterField(
            model_name='eventomanejo',
            name='peso_medio',
            field=models.DecimalField(decimal_places=3, help_text='Peso médio em kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lote',
            name='peso_medio_atual',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso médio atual em kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lote',
            name='peso_medio_inicial',
            field=models.DecimalField(decimal_places=3, help_text='Peso médio inicial em kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
