# Generated by Django 5.1.7 on 2025-09-27 23:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0016_alter_arracoamentorealizado_data_edicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curvacrescimento',
            name='peso_pretendido',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Peso pretendido (em g)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='curvacrescimentodetalhe',
            name='arracoamento_biomassa_perc',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual de arraçoamento sobre a biomassa (%BW/dia)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='curvacrescimentodetalhe',
            name='ganho_de_peso',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Ganho de peso total no período (em g)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='curvacrescimentodetalhe',
            name='gpd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Ganho de Peso Diário (g)'),
        ),
        migrations.AlterField(
            model_name='curvacrescimentodetalhe',
            name='peso_final',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso final do animal no período (em g)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='curvacrescimentodetalhe',
            name='peso_inicial',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso inicial do animal no período (em g)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventomanejo',
            name='peso_medio',
            field=models.DecimalField(decimal_places=3, help_text='Peso médio em gramas (g)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lote',
            name='peso_medio_atual',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Peso médio atual em gramas (g)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lote',
            name='peso_medio_inicial',
            field=models.DecimalField(decimal_places=3, help_text='Peso médio inicial em gramas (g)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='biomassa_inicial',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Biomassa no início do dia (kg)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='biomassa_projetada',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Biomassa projetada para o FIM do dia (g)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='biomassa_real',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Biomassa real no FIM do dia (g)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='gpd_projetado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPD Projetado (g)'),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='gpd_real',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPD Real (g)'),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='gpt_projetado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPT Projetado (g)'),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='gpt_real',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GPT Real (g)'),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='peso_medio_inicial',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso médio no início do dia (g)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='peso_medio_projetado',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso médio projetado para o FIM do dia (g)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='peso_medio_real',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso médio real no FIM do dia (g)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comprimento em metros (m)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largura em metros (m)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='metro_cubico',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Volume em metros cúbicos (m³)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='metro_quadrado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Área em metros quadrados (m²)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='profundidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profundidade em metros (m)', max_digits=10, null=True),
        ),
    ]
