# Generated by Django 5.1.7 on 2025-09-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0017_alter_curvacrescimento_peso_pretendido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotediario',
            name='biomassa_projetada',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Biomassa projetada para o FIM do dia (kg)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lotediario',
            name='biomassa_real',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Biomassa real no FIM do dia (kg)', max_digits=12, null=True),
        ),
    ]
