# Generated by Django 5.1.7 on 2025-07-06 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_empresa', models.CharField(choices=[('pj', 'Pessoa Jurídica'), ('pf', 'Pessoa Física')], max_length=10)),
                ('cnae', models.CharField(blank=True, max_length=20, null=True)),
                ('cnae_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('nome_representante', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_representante', models.CharField(blank=True, max_length=20, null=True)),
                ('email_representante', models.EmailField(blank=True, max_length=254, null=True)),
                ('status_empresa', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=20)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.categoriaempresa')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaAvancada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(choices=[('pj', 'Pessoa Jurídica'), ('pf', 'Pessoa Física')], max_length=10)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('regime_tributario', models.CharField(blank=True, choices=[('SN', 'Simples Nacional'), ('LP', 'Lucro Presumido'), ('LR', 'Lucro Real')], help_text='Regime tributário da empresa para fins fiscais.', max_length=2, null=True, verbose_name='Regime Tributário')),
                ('contribuinte_icms', models.BooleanField(default=False, help_text='Indica se a empresa é contribuinte do ICMS.', verbose_name='Contribuinte ICMS')),
                ('inscricao_municipal', models.CharField(blank=True, help_text='Inscrição Municipal da empresa (para serviços).', max_length=20, null=True, verbose_name='Inscrição Municipal')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('cnae_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('cnae_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('contato_financeiro_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('contato_financeiro_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato_financeiro_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('contato_financeiro_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('contato_comercial_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('contato_comercial_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato_comercial_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('contato_comercial_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('condicao_pagamento', models.CharField(blank=True, max_length=255, null=True)),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.BooleanField(default=False)),
                ('fornecedor', models.BooleanField(default=False)),
                ('status_empresa', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=20)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.categoriaempresa')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
