# Generated by Django 5.1.7 on 2025-07-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaavancada',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresaavancada',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
