# Generated by Django 5.1.7 on 2025-11-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome comercial do cliente/tenant', max_length=150)),
                ('slug', models.SlugField(help_text="Identificador único para URLs e diretórios (e.g., 'cliente-a')", unique=True)),
                ('dominio', models.CharField(help_text="Domínio ou subdomínio para acesso (e.g., 'cliente-a.onetech.app')", max_length=255, unique=True)),
                ('db_name', models.CharField(max_length=100, unique=True)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=100)),
                ('db_host', models.CharField(default='127.0.0.1', max_length=100)),
                ('db_port', models.CharField(default='3306', max_length=10)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(help_text='Formato: XX.XXX.XXX/XXXX-XX', max_length=18)),
                ('ie', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('certificado_a1', models.FileField(blank=True, help_text='Arquivo .pfx ou .p12', null=True, upload_to='tenants/certificados/')),
                ('senha_certificado', models.CharField(blank=True, help_text='Senha do arquivo de certificado digital', max_length=128)),
                ('csc', models.CharField(blank=True, max_length=64, verbose_name='CSC/Token')),
                ('id_token', models.CharField(blank=True, max_length=32, verbose_name='ID do Token CSC')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant (Cliente)',
                'verbose_name_plural': 'Tenants (Clientes)',
            },
        ),
    ]
