# Generated by Django 5.1.7 on 2025-11-17 23:04

import control.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='certificado_a1',
            field=models.FileField(blank=True, help_text='Arquivo .pfx ou .p12', null=True, upload_to=control.utils.tenant_media_path),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=control.utils.tenant_media_path),
        ),
    ]
