# Generated by Django 5.1.7 on 2025-11-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_tenant_certificado_a1_alter_tenant_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logos_emitentes/', verbose_name='Logotipo')),
                ('is_default', models.BooleanField(default=False, help_text='Marque se este é o emitente padrão para novas transações.', verbose_name='Padrão')),
            ],
            options={
                'verbose_name': 'Emitente (Matriz/Filial)',
                'verbose_name_plural': 'Emitentes (Matriz/Filiais)',
            },
        ),
    ]
