# Generated by Django 5.1.7 on 2025-11-21 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_emitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='emitente_padrao',
            field=models.ForeignKey(blank=True, help_text='Emitente padrão associado a este tenant para operações fiscais.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='control.emitente'),
        ),
    ]
