# Generated by Django 5.1.7 on 2026-03-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_tenant_emitente_padrao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'permissions': [('view_admin_menu', 'Pode visualizar submenu Admin'), ('view_django_admin_link', 'Pode visualizar link do Painel Django')], 'verbose_name': 'Tenant (Cliente)', 'verbose_name_plural': 'Tenants (Clientes)'},
        ),
    ]
